services:
  - type: web
    name: collaborative-project-tracker
    env: node
    plan: free
    region: singapore
    branch: master
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/v1/healthCheck
    envVars:
      - key: SERVICE_NAME
        value: "TESTING"
      - key: NODE_ENV
        value: "production"
      - key: PORT
        value: "3001"
      - key: ID
        value: "1"
      - key: BROKER_REDIS_NAME
        value: "project-tracker"
      - key: BROKER_REDIS_HOST_URL
        value: "localhost"
      - key: BROKER_REDIS_PORT
        value: "6379"
      - key: BROKER_REDIS_PASSWORD
        value: "NONE"
      - key: BROKER_REDIS_PUBLISHER
        value: "0"
      - key: BROKER_REDIS_SUBSCRIBER
        value: "0"
      - key: BROKER_REDIS_CACHE
        value: "1"
      - key: BROKER_REDIS_SUB_TOPICS
        value: "NONE"
      - key: LOG_DB_URI
        value: "your-log-db-connection-string"
      - key: LOG_DB_NAME
        value: "ANKUSH"
      - key: DB_URL
        value: "your-database-connection-string"
      - key: ENCRYPTION_SECRET_KEY
        value: "your-encryption-key"
      - key: ENCRYPTION_METHOD
        value: "AES-256-CBC"
      - key: JWT_SECRET
        value: "your-jwt-secret"
      - key: JWT_EXPIRY_DAYS
        value: "7"